### ISSUE TITLE
Name change for multiple gorga and haples

### ISSUE THREAD

**Issue by t-bullock** [t-bullock/kassia#7]
From @ilizol:
> Could be better to change
> digorg -> gorg2
> trigorg -> gorg3
> ?
> 
> Same with haple
> dipl -> hapl2
> trip -> hapl3
> tetr -> hapl4
> ?

We do specify kentimata as ken2, and we discussed naming kentima as ken1, so the suggestion for hap1, hap2, hap3 would be consistent with ken2. On the other hand, diple, triple, etc. do have their own names in Byzantine Notation (they aren't really referred to as "2 haples" or "3 haples") and keeping with diple, triple, etc. would be more consistent with their names in the Unicode block. @barudaret might have to weight in on this.

**Comment by anaskaejdar** [comment]
We could do something like that, but I agree with Trevor, saying "hapl2" doesn't feel right.  I said it in matrix a few days ago, but I think Charalampos's way of doing it is really well-done.

gorg = g
digorg = gg
trigorg = ggg

hapl = t (or apl)
dipl = tt
trip = ttt
tetr = tttt

kent = k
ken2 = kk

This way saves keystrokes and doesn't sacrifice in readability.  I feel better about saying ttt than hapl3, but maybe there's a better letter to use than t for this purpose, idk

**Comment by ilizol** [comment]
The only reason that I suggest this is for consistency reasons. The names must have 4 characters and the same logic in my opinion. The save of keystrokes is not an important thing in a universal encoding method.

**Comment by anaskaejdar** [comment]
One thing to consider is readability.  Once we add positioning info, any of these names that end in a number will suddenly be much harder to read.  That includes ken2.  Think about `olig_aposUL_ken2UR_gorg2U2R` as opposed to `olig_aposUL_kkUR_ggU2R`.  The difference isn't tremendous.  But reading the former, one might think "olig_apos_kenU2R_gorgU2R2"

**Comment by t-bullock** [comment]
Yeah, less numbers is probably better to avoid confusion with positions.
